# Generated by Django 3.0.6 on 2020-05-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typing_on_slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_typing', models.TextField()),
                ('second_typing', models.TextField()),
            ],
        ),
    ]
