# Generated by Django 3.0.6 on 2020-05-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iok', '0004_legend_president'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_u',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
