# Generated by Django 3.0.6 on 2020-05-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iok', '0005_about_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_u',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
