# Generated by Django 3.0.6 on 2020-05-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iok', '0006_about_u_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_u',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
