# Generated by Django 3.0.6 on 2020-05-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iok', '0007_auto_20200523_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.TextField()),
                ('instagram', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
