# Generated by Django 3.0.6 on 2020-05-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iok', '0008_media_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPointTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.ManyToManyField(to='iok.TeamPointTable')),
            ],
        ),
    ]
