# Generated by Django 3.0.6 on 2020-05-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iok', '0010_auto_20200523_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idare_heyeti',
            name='photo',
            field=models.ImageField(upload_to='idare_heyeti'),
        ),
    ]
